task: tiny_offline_arithmetic_multiplication_generative
dataset_path: csv
dataset_kwargs:
  data_files: !function ../default/utils.null_dataset_path
process_docs: !function ../default/utils.create_multiplication_dataset
output_type: generate_until
test_split: train
description: ""
doc_to_text: prompt
doc_to_target: "{{['A', 'B', 'C', 'D'][answer_index]}}"
generation_kwargs:
  until:
    - "</s>"
    - "\n"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_punctuation: true
    ignore_case: true
filter_list:
  - name: get_response
    filter:
      # Filter everything after the first break line
      - function: "regex"
        regex_pattern: "^(.*?)(?=\\n|$)"
      # Remove leading white spaces
      - function: remove_whitespace
      # function to ignore right white spaces or line breaks
      - function: "regex"
        regex_pattern: "^(.*?)\\s*$"
      # function to get just the first character of the response
      - function: "regex"
        regex_pattern: "(^.{0,1}){1}"
      - function: take_first
metadata:
  version: 1.0